### ISSUE TITLE
Error when changing patient info

### ISSUE THREAD

**Issue by rsfutch77** [hpearl725/SFWE_403_TEAM_1#14] opened 2023-10-19 02:12 UTC
![image](https://github.com/hpearl725/SFWE_403_TEAM_1/assets/26337219/52c824a1-4910-4123-b638-3c9c6c0bf8b8)

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\rsfutch77\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__   
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\rsfutch77\Desktop\Working\swfe_workspace\SFWE_403_TEAM_1\GUI\patients_table.py", line 108, in <lambda>
  File "C:\Users\rsfutch77\Desktop\Working\swfe_workspace\SFWE_403_TEAM_1\GUI\patients_table.py", line 139, in save_edits
  File "C:\Users\rsfutch77\AppData\Local\Programs\Python\Python311\Lib\csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsfutch77\AppData\Local\Programs\Python\Python311\Lib\csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: ''

**Comment by rsfutch77** [comment] 2023-10-19 02:13
Even though it shows the error, the patient info still seemed to update correctly.

**Comment by rsfutch77** [comment] 2023-10-19 02:30
Seems to fix itself after the first time the error happens:
![image](https://github.com/hpearl725/SFWE_403_TEAM_1/assets/26337219/c7c63cce-3659-4e24-9d7e-39d4516e5ec6)

**Comment by jowenss721** [comment] 2023-10-19 04:29
I can't reproduce this on my Windows machine, but it looks like this is happening because of the extra comma-separated entries in the csv file. This isn't an issue with our code but rather the placeholder csv file we're using right now — this should go away after @hpearl725 finishes the user refactor

**Comment by jowenss721** [comment] 2023-10-19 23:37
Resolved by [PR #15](https://github.com/hpearl725/SFWE_403_TEAM_1/pull/15)

**Closed as completed by jowenss721** 2023-10-19 23:37 UTC
Labels: bug
